language: python
python: 2.7

env:
  - TOX_ENV=py27
  - TOX_ENV=docs
  - TOX_ENV=pylint
  - TOX_ENV=flake8

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

deploy:
  provider: pypi
  user: mhubig
  password:
    secure: V3FcCr361MDnurFXx02+oZVLOBEJaPnmhK0Pm5jnh9S2RkH5b75uNkqwbx5oWB9SrEpPjy5A+wnTAntSGjfeDt1CxXBLZmcxHXHPfoiiiPAyVzI7OVL9K69G9ff1LU4lYRDEWnSKnnYDcviBwdXSZr4QRyefReeIDF6I9CAbO2c=
  on:
    tags: true
    branch: master
    repo: mhubig/implib2
