sudo: false
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install --user tox-travis
  - pip install --user codecov

script: tox

after_success:
  - codecov

deploy:
  provider: pypi
  user: mhubig
  password:
    secure: V3FcCr361MDnurFXx02+oZVLOBEJaPnmhK0Pm5jnh9S2RkH5b75uNkqwbx5oWB9SrEpPjy5A+wnTAntSGjfeDt1CxXBLZmcxHXHPfoiiiPAyVzI7OVL9K69G9ff1LU4lYRDEWnSKnnYDcviBwdXSZr4QRyefReeIDF6I9CAbO2c=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    branch: master
    repo: mhubig/implib2
