language: python

python:
    - 2.7

install:
    - pip install -r requirements.txt --use-mirrors
    - pip install -r requirements-docs.txt --use-mirrors
    - pip install -r requirements-tests.txt --use-mirrors
    - pip install coveralls --use-mirrors
    - python setup.py install

script:
    - py.test --cov-report xml --cov-report term-missing --cov implib2 --junitxml=unittests.xml tests
    - pylint --rcfile=pylint.rc tests
    - pylint --rcfile=pylint.rc implib2
    - cd docs
    - sphinx-build -W -b html -d _build/doctrees . _build/html
    - cd ..

after_success:
- coveralls

deploy:
  provider: pypi
  user: mhubig
  password:
    secure: V3FcCr361MDnurFXx02+oZVLOBEJaPnmhK0Pm5jnh9S2RkH5b75uNkqwbx5oWB9SrEpPjy5A+wnTAntSGjfeDt1CxXBLZmcxHXHPfoiiiPAyVzI7OVL9K69G9ff1LU4lYRDEWnSKnnYDcviBwdXSZr4QRyefReeIDF6I9CAbO2c=
  on:
    tags: true
    branch: master
    repo: mhubig/implib2
